version: '3'
services:
  nginx:
    build: ./nginx
    links:
        - gunicorn1:gunicorn1
        - gunicorn2:gunicorn2
        - gunicorn3:gunicorn3
        - node1:node1
        - node2:node2
        - node3:node3
    ports:
        - "5050:5050"
        - "5000:5000"
        - "5555:5555"

  flask:
    build:
      context: .
      dockerfile: ./flask/Dockerfile
    ports:
     - "9000:8080"
  
  gunicorn1:
    build: 
      context: .
      dockerfile: ./gunicorn/Dockerfile
    ports:
     - "7000:8080"
    volumes:
     - ./gunicorn/app.py:/code/app.py

  gunicorn2:
    build: 
      context: .
      dockerfile: ./gunicorn/Dockerfile
    ports:
     - "8080"
    volumes:
     - ./gunicorn/app.py:/code/app.py
     
  gunicorn3:
    build: 
      context: .
      dockerfile: ./gunicorn/Dockerfile
    ports:
     - "8080"
    #~ volumes:
     #~ - .:/code
     
  node1:
    build: 
      context: .
      dockerfile: ./node/Dockerfile
    ports:
     - "9090:8080"
    #~ volumes:
     #~ - .:/code
     
  node2:
    build: 
      context: .
      dockerfile: ./node/Dockerfile
    ports:
     - "8080"
    #~ volumes:
     #~ - .:/code
  
  node3:
    build: 
      context: .
      dockerfile: ./node/Dockerfile
    ports:
     - "8080"
    #~ volumes:
     #~ - .:/code

  redis:
    image: "redis:alpine"

  grafana_graphite:
    image: kamon/grafana_graphite
    container_name: grafana-dashboard
    ports:
      - "80:80"
      - "81:81"
      - "2003:2003"
      #~ - "2023-2024:2023-2024"
      - "8125:8125/udp"
      - "8126:8126"
    volumes:
      - ./data/whisper:/opt/graphite/storage/whisper
      - ./data/grafana:/opt/grafana/data
      - ./log/graphite:/opt/graphite/storage/log
      - ./grafana/dashboards:/src/dashboards
